### ISSUE TITLE
Cannot find App Shell module

### ISSUE THREAD

**Issue by carvinlo** [FlorianRappl/piral-webpack-tools#1]
Error Message:
```bash
ERROR in [at-loader] ./src/index.tsx:1:25 
    TS2307: Cannot find module 'piral-demo'.
ℹ ｢wdm｣: Failed to compile.
```

**Comment by FlorianRappl** [comment]
I think I need a bit more infos / a MWE to reproduce the issue.

Sure everything is installed and set up correctly?

**Comment by carvinlo** [comment]
> Error Message:
> 
> ```shell
> ERROR in [at-loader] ./src/index.tsx:1:25 
>     TS2307: Cannot find module 'piral-demo'.
> ℹ ｢wdm｣: Failed to compile.
> ```

Run with `pilet debug-wp`

**Comment by carvinlo** [comment]
> I think I need a bit more infos / a MWE to reproduce the issue.
> 
> Sure everything is installed and set up correctly?

The app shell and the pilet are in one Mono Repo, `piral-cli-webpack` was install in the pilet, then run pilet with `pilet debug-wp`.

**Comment by FlorianRappl** [comment]
I see - right now there is no (direct) support for `piral-cli-webpack` on the mono repo use. It is supported in the Parcel flow, though.

We can look into it.

As a workaround you could build the app shell and "install" (i.e., link it) locally (e.g., in the pilet). This is, obviously, cumbersome and one would love the implicitness of a monorepo, however, the `debug` mode needs to support this.

I'll leave it open as an enhancement and we'll cover it with the next release.

**Comment by carvinlo** [comment]
Thanks!
