### ISSUE TITLE
How to publish a pilet built by webpack

### ISSUE THREAD

**Issue by carvinlo** [FlorianRappl/piral-webpack-tools#13]
When publishing, `pilet publish` internally calls the parcel build command, so how to publish the pilet built using webpack?

**Comment by FlorianRappl** [comment]
You can just build it, pack it and publish it.

Only publish with `--fresh` calls the standard build command. Without `--fresh` it just uses *.tgz or the tgz that you specified.

One example is:

```sh
pilet build-wp && pilet pack && pilet publish --url ... -api-key ... && rm *.tgz
```

**Comment by carvinlo** [comment]
Got it, thanks!

**Comment by FlorianRappl** [comment]
One more remark @carvinlo:

With 0.11.5 of the Piral CLI we will also introduce the pluggable build system. Then the webpack integration will change such that `piral build` or `pilet build` will resolve to webpack (if this plugin is installed).

As a result `pilet publish` with `--fresh` will use webpack in this case!

I'll let you know when we are there.

**Comment by carvinlo** [comment]
> One more remark @carvinlo:
> 
> With 0.11.5 of the Piral CLI we will also introduce the pluggable build system. Then the webpack integration will change such that `piral build` or `pilet build` will resolve to webpack (if this plugin is installed).
> 
> As a result `pilet publish` with `--fresh` will use webpack in this case!
> 
> I'll let you know when we are there.

Waiting for good news !
