### ISSUE TITLE
Error: No converter for component of type "undefined" registered.

### ISSUE THREAD

**Issue by carvinlo** [FlorianRappl/piral-webpack-tools#16]
# Bug Report

For more information, see the `CONTRIBUTING` guide.

## Prerequisites

- [ ] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version?
- [ ] Did you perform a search in the issues?

## Environment Details and Version

piral-cli@0.11.5
piral-cli-webpack@0.5.3
Chrome@latest

## Description

update piral-cli@0.11.5 and use piral-lazy
```
import { PiletApi } from '<name-of-piral-instance>';

export function setup(piral: PiletApi) {
  const LazyPage = piral.fromLazy(() => import('./MyPage'));
  piral.registerPage('/sample', LazyPage);
}
```

## Steps to Reproduce

1. [First Step]
2. [next step...]

## Expected behavior

[What you expected to happen]

## Actual behavior

[What actually happened]

## Possible Origin / Solution

[Optionally, share your idea to fix the issue]

**Comment by FlorianRappl** [comment]
Can you show the content of `MyPage`?

Note that if `MyPage` is a React component you'd should use `React.lazy` (no converter required). Otherwise, you'd need to export a general component, which must have a `type` field.

For a Vue component (example) the easiest way would be to use `fromVue`:

```ts
// assumes that the export is like module.exports = MyVueComponent;
const LazyPage = piral.fromLazy(() => import('./MyPage').then(res => piral.fromVue(res)));
```

**Comment by carvinlo** [comment]
> Can you show the content of `MyPage`?
> 
> Note that if `MyPage` is a React component you'd should use `React.lazy` (no converter required). Otherwise, you'd need to export a general component, which must have a `type` field.

`MyPage` is a React component.
Just want to Improve it into a [piral-lazy-deps](https://github.com/smapiot/piral/issues/180#issuecomment-629690236) plugin base on `piral-lazy`.
```ts
export function setup(app) {
  app.registerDependency('redux', () => import('redux'));
  app.registerPage('/foo', app.lazy(() => import('./Foo'), ['redux']);
}
```

**Comment by FlorianRappl** [comment]
Yeah so that piral-lazy-deps is not yet in Piral. We should open a dedicated issue to track that.

I guess it makes sense to put it in `piral-lazy`, too. Also I guess it makes sense that the `fromLazy` of Piral could work with React components, too, even though we should still recommend using `React.lazy` usually.

Do you want to create a dedicated issue in [the repo](https://github.com/smapiot/piral/issues)? You can reference the previous discussion.

Thanks!

**Comment by carvinlo** [comment]
Awsome [#226](https://github.com/smapiot/piral/issues/226)

**Comment by carvinlo** [comment]
Great, It works fine !
