### ISSUE TITLE
After reinstalling dependencies using `yarn`,` yarn build` went wrong

### ISSUE THREAD

**Issue by carvinlo** [FlorianRappl/piral-webpack-tools#17]
![image](https://user-images.githubusercontent.com/5674761/83317969-71077e80-a263-11ea-92fb-18e86fcbaa7b.png)
It seems that the `schema-utils` package officially released a compatibility issue caused by the new version

>It is okay to keep the `yarn.lock` file, but this repository needs to be integrated into the [piral](https://github.com/smapiot/piral) repository for development and debugging, so the original `yarn.lock` cannot be retained

## Possible Origin / Solution
Replace
```
schema-utils@^2.5.0, schema-utils@^2.6.1, schema-utils@^2.6.5, schema-utils@^2.6.6:
  version "2.7.0"
  resolved "https://registry.npmjs.org/schema-utils/-/schema-utils-2.7.0.tgz#17151f76d8eae67fbbf77960c33c676ad9f4efc7"
  integrity sha512-0ilKFI6QQF5nxDZLFn2dMjvc4hjg/Wkg7rHd3jK6/A4a1Hl9VFdQWvgB1UMGoU94pad1P/8N7fMcEnLnSiju8A==
  dependencies:
    "@types/json-schema" "^7.0.4"
    ajv "^6.12.2"
    ajv-keywords "^3.4.1"
```
with
```
schema-utils@^2.5.0, schema-utils@^2.6.1, schema-utils@^2.6.5, schema-utils@^2.6.6:
  version "2.6.6"
  resolved "https://registry.yarnpkg.com/schema-utils/-/schema-utils-2.6.6.tgz#299fe6bd4a3365dc23d99fd446caff8f1d6c330c"
  dependencies:
    ajv "^6.12.0"
    ajv-keywords "^3.4.1"
```
it works fine

**Comment by FlorianRappl** [comment]
Thanks for finding this. We'll resolve it with the next version!
