### ISSUE TITLE
Pilets built with Webpack seem to be using first chunk emitted as the Pilet

### ISSUE THREAD

**Issue by rtruong** [FlorianRappl/piral-webpack-tools#22]
We're running into an issue with Piral and Webpack. When running in debug mode (i.e., `pilet debug`), if the Webpack build emits more than one chunk, it tries to load the wrong chunk as the pilet. More specificially, it tries to load the first chunk emitted by the Pilet's webpack build.

For example, if we use Font Awesome 4, the chunks emitted include font files. So, when running pilet debug, it ends up trying to load an `.eot` file as the pilet.

Another example, if we do code splitting with `React.lazy()` and `import()`, the chunks emitted are `0.index.js` and `index.js`. In that case, it tires to load `0.index.js` as the pilet, which is incorrect.

**Comment by FlorianRappl** [comment]
Closing in favor of https://github.com/smapiot/piral/issues/258.

Thanks for reporting the issue :+1:!
