### ISSUE TITLE
Need support for favicon

### ISSUE THREAD

**Issue by lamson-dev** [FlorianRappl/piral-webpack-tools#23]
While trying out piral-cli-webpack@0.11.8 to build piral instance
I noticed my output index.html is missing the favicon

Notes:
It seems we can add https://github.com/jantimon/favicons-webpack-plugin to support this use case

**Comment by lamson-dev** [comment]
Here is my proposal from looking at the code. 

Update in https://github.com/FlorianRappl/piral-webpack-tools/blob/master/packages/html5-entry-webpack-plugin/src/index.ts

- From a 'zero config' standpoint, the piral instance dev just needed to add `logo.png` to their webpack context folder.

```
  const FaviconsWebpackPlugin = require('favicons-webpack-plugin')
  ...
  apply(compiler: Compiler) {
    const entry = compiler.options.entry;
    const [template] = getTemplates(entry);

    if (template) {
      const src = dirname(template);
      const templateContent = load(readFileSync(template, 'utf8'));
      const entries = extractParts(templateContent).map(entry => join(src, entry));
      const plugins = [
        new HtmlWebpackPlugin({
          templateContent: templateContent.html(),
        }),
        new FaviconsWebpackPlugin(),
      ];

      setEntries(compiler.options, template, entries);
      plugins.forEach(plugin => plugin.apply(compiler));
    }
  }
```

- Full solution (not sure if this will work)
```
  const FaviconsWebpackPlugin = require('favicons-webpack-plugin')
  ...
  apply(compiler: Compiler) {
    const entry = compiler.options.entry;
    const [template] = getTemplates(entry);

    if (template) {
      const src = dirname(template);
      const templateContent = load(readFileSync(template, 'utf8'));
      const entries = extractParts(templateContent).map(entry => join(src, entry));
      const plugins = [
        new HtmlWebpackPlugin({
          templateContent: templateContent.html(),
        }),
      ];
     
      if (entry.endsWith('favicon.ico') {
         plugins.push(new FaviconsWebpackPlugin({ 
            logo: entry,
            prefix: publicUrl // need to get this from somewhere
         }))
      }

      setEntries(compiler.options, template, entries);
      plugins.forEach(plugin => plugin.apply(compiler));
    }
  }
```

**Comment by carvinlo** [comment]
I also encountered a similar scenario, which needed to be completed in collaboration with `html-webpack-plugin`. At present, I found one thing in common, that is, most plug-ins that need to work with `html-webpack-plugin`'s [hooks](https://github.com/jantimon/html-webpack-plugin/blob/master/lib/hooks.js#L93). We can do this to share hooks:
```js
import { dirname } from 'path';
const HtmlWebpackPlugin = require(require.resolve('html-webpack-plugin', { paths: [dirname(require.resolve('html5-entry-webpack-plugin'))] }));
// ...
```
And then push a pr to [favicons-webpack-plugin](https://github.com/jantimon/favicons-webpack-plugin/blob/master/src/index.js#L79) to support the `HtmlWebpackPlugin` option, such as:
```js
new FaviconsWebpackPlugin({
  HtmlWebpackPlugin,
  logo: entry,
  prefix: publicUrl // need to get this from somewhere
})
```
This will achieve the goal and keep `html5-entry-webpack-plugin` simple, hope that helps.

**Comment by FlorianRappl** [comment]
Sounds like a good idea, but it depends heavily that the `favicons-webpack-plugin` maintainer(s) accept this PR. I am no sure here (but I have no clue, maybe they are indeed very open about it...).

We could give it a try. Thanks for the great idea @carvinlo !

**Comment by FlorianRappl** [comment]
With the latest change the `favicons-webpack-plugin` will just work.
