### ISSUE TITLE
Set no-cache in debugging of pilets

### ISSUE THREAD

**Issue by carvinlo** [FlorianRappl/piral-webpack-tools#3]
Need to clear cache manually to update, when change the pilet code in debug mode.

**Comment by FlorianRappl** [comment]
I think I'll need more infos. What cache? Webpack's cache? What behavior do you see and what do you expect?

**Comment by carvinlo** [comment]
> I think I'll need more infos. What cache? Webpack's cache? What behavior do you see and what do you expect?

I think It is browser cache.
The browser refreshed after modifying the pilet code, but the content not update.
Then the `index.dev.js` resource request is cache from disk.
If clear the browser cache manually and refresh, the content will be updated.
system: windows
browser: chrome

**Comment by FlorianRappl** [comment]
Thanks for the info - for me it always updated, but I guess it may be due to my debugging settings (which prevents caching).

In general we should send a `no-cache` header, too. Will be done with the next release.
