### ISSUE TITLE
Nested packaging

### ISSUE THREAD

**Issue by carvinlo** [FlorianRappl/piral-webpack-tools#4]
Before building the compressed tgz package again, the previously packaged tgz package is not cleaned up, resulting in nesting, as shown below:
<img width="775" alt="截屏2020-04-23 下午9 44 41" src="https://user-images.githubusercontent.com/5674761/80105441-3303a480-85ab-11ea-89a2-6a6dc978becb.png">

**Comment by carvinlo** [comment]
Use build commands: `piral build-wp`

**Comment by FlorianRappl** [comment]
Thanks. Yes we do not clean up beforehand (which is something we do in the Parcel way).

We should do here, too.
