### ISSUE TITLE
`pilet-webpack-plugin` ignores externals function

### ISSUE THREAD

**Issue by carvinlo** [FlorianRappl/piral-webpack-tools#40]
pilet's `webpack.config.js`:

```ts
module.exports = (config) => {
  const externals = [
    (context, request, callback) => {
      // Won't execute here
      callback();
    },
  ];
  const current = config.externals;
  config.externals = Array.isArray(current)
    ? [...current, ...externals]
    : current
    ? [current, ...externals]
    : externals;

  return config;
};
```

[pilet-webpack-plugin](https://github.com/FlorianRappl/piral-webpack-tools/blob/55c393b799e7a1f84269dc666e66936491b9513e/packages/pilet-webpack-plugin/src/helpers.ts#L72) ignores externals function

**Comment by FlorianRappl** [comment]
Yeah what should we do in this case? The plugin needs to set the externals, which is difficult if you want to have full control over them. My suggestion is to override this completely and take care of that yourself.

**Comment by carvinlo** [comment]
pilet's `webpack.config.js`:

```ts
class ExternalWebpackPlugin implements Plugin {
  apply(compiler: Compiler) {
    compiler.hooks.afterEnvironment.tap('externalWebpackPlugin', () => {
      const externals = [
        (context, request, callback) => {
          callback();
        },
      ];
      const current = compiler.options.externals;
      compiler.options.externals = Array.isArray(current)
        ? [...current, ...externals]
        : current
          ? [current, ...externals]
          : externals;
    });
  }
}
module.exports = (config) => {
  config.plugins.push(
    new ExternalWebpackPlugin(),
  );

  return config;
};
```

It seems to be working fine so far, but this way will go wrong in schema (`v2`), right?

**Comment by FlorianRappl** [comment]
Yes I think so. Since `v2` (i.e., that change was also pushed "down") the externals should use the object syntax: https://github.com/FlorianRappl/piral-webpack-tools/blob/master/packages/pilet-webpack-plugin/src/helpers.ts#L68

**Comment by carvinlo** [comment]
Thanks for your quick response! 
Is it possible to distinguish the conversion of `externals`?
See [https://github.com/carvinlo/piral-webpack-tools/commit/acc205849ed5421eab2f93020e974bfade35cce2](https://github.com/carvinlo/piral-webpack-tools/commit/acc205849ed5421eab2f93020e974bfade35cce2)

**Comment by FlorianRappl** [comment]
Maybe, but I'm not sure I'd recommend it.

Potentially the best way is to *always* have the array, but *only* with a single object inside. So we still do what we do today (using the object-notation for webpack), but we "wrap" it in an array. This way, you could just append your function (or anything else), while still being able to manipulate the original contents (now with `externals[0]["name-of-external"]` instead of `externals["name-of-external"]`).

**Comment by carvinlo** [comment]
See [https://github.com/carvinlo/piral-webpack-tools/commit/c5f5f7da47b7592a48cbbe5683751029f72c959b](https://github.com/carvinlo/piral-webpack-tools/commit/c5f5f7da47b7592a48cbbe5683751029f72c959b). Is that correct?

**Comment by FlorianRappl** [comment]
Yeah LGTM! Awesome :rocket:
